name: CI

on:
  push: {}
  pull_request: {}

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Lua and luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks

      - name: Install luacheck
        run: |
          luarocks install luacheck

      - name: Run luacheck
        run: |
          luacheck .
